name: Build and Deploy Lovable

# Trigger this workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # use version compatible with your project

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build project (creates dist folder)
      - name: Build project
        run: npm run build

      # Step 5: Deploy dist folder to gh-pages branch
      - name: Deploy to GitHub Pages
        run: npx gh-pages -d dist
